export const SET_USER = "SET_USER";
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_UNAUTHENTICATED = "SET_UNAUTHENTICATED";

export const SET_PLAYLISTS = "SET_PLAYLISTS";
export const SET_SELECTED_PLAYLIST = "SET_SELECTED_PLAYLIST";
export const RELOAD_GAME_STATE = "RELOAD_GAME_STATE";
